export const DesignationList = [
    "Administrative Services Manager",
    "Administrative Law Judge",
    "Aircraft Structure",
    "Aircraft Mechanic",
    "Administrative Assistant",
    "Adhesive Bonding Machine Operator",
    "Aerospace Engineering And Operations Technician",
    "Agricultural Inspector",
    "Attendant",
    "Agricultural Equipment Operator",
    "Agricultural Worker",
    "Air Traffic Controller",
    "Architectural And Civil Drafter",
    "Bench Carpenter",
    "Business Operations Specialist",
    "Civil Engineer",
    "Clerk",
    "Collector",
    "Correspondent",
    "Crane And Tower Operator",
    "Derrick Operator",
    "Electrical Power-line Installer",
    "Engineer",
    "Environmental Scientist",
    "Etcher",
    "Farm Labor Contractor",
    "Fiberglass Laminator",
    "Financial Examiner",
    "First-line Supervisors Of Police And Detective",
    "Floral Designer",
    "Food Service Manager",
    "Healthcare Support Worker",
    "Homeland Security ",
    "Industrial Machinery Mechanic",
    "Infantry Officer ",
    "Insurance Claims Clerk ",
    "Interpreter Or Translator ",
    "Advertising Sales Agent",
    "Agricultural Sciences Teacher",
    "All Occupation",
    "Architecture Teacher",
    "Audio-visual And Multimedia Collections Specialist",
    "Automotive Service Technician",
    "Astronomer",
    "Bailiff",
    "Barber",
    "Blockmason",
    "Bill And Account Collector",
    "Boilermaker",
    "Budget Analyst",
    "Claims Adjuster",
    "Captain",
    "Coil Winder",
    "Career/technical Education Teacher",
    "Combined Food Preparation And Serving Worker",
    "Coin",
    "Compensation And Benefits Manager",
    "Compliance Officer",
    "Composer",
    "Concrete Finisher",
    "Computer And Mathematical Occupation",
    "Construction Laborer",
    "Conservation Scientist",
    "Cost Estimator",
    "Construction Manager",
    "Costume Attendant",
    "Cook",
    "Database Administrator",
    "Correctional Officer",
    "Designer",
    "Criminal Investigator",
    "Detective",
    "Dental Assistant",
    "Door-to-door Sales Worker",
    "Diagnostic Medical Sonographer",
    "Electrical And Electronics Engineering Technician",
    "Dietitian",
    "Escort",
    "Editor",
    "Extraction Worker",
    "Electronics Engineer",
    "Extruding",
    "Engraver",
    "Fine Artist",
    "Environmental Engineer",
    "First-line Supervisors Of Construction Trade",
    "Forest Fire Inspector",
    "First-line Supervisors Of Farming",
    "Gaming Cage Worker",
    "Fisher",
    "Gaming And Sports Book Writer",
    "Food Batchmaker",
    "Glazier",
    "Food Cooking Machine Operator",
    "Hazardous Materials Removal Worker",
    "Foundry Mold And Coremaker",
    "Healthcare Social Worker",
    "Geography Teacher",
    "Graduate Teaching Assistant",
    "Hoist And Winch Operator ",
    "Grounds Maintenance Worker",
    "Human Resources Specialist ",
    "Hr Manager ",
    "Information Clerk",
    "History Teacher ",
    "Insurance Underwriter",
    "Hoist And Winch Operator",
    "Jeweler",
    "Human Resources Assistant ",
    "Jeweler ",
    "Illustrator ",
    "Industrial Machinery Mechanic ",
    "Installation And Repair Technician ",
    "Insurance Appraiser",
    "Interior Designer ",
    "Interviewer ",
    "Investigator",
    "Aerospace Engineer",
    "Animal Breeder",
    "Automotive Glass Installer",
    "Bellhop",
    "Cabinetmaker",
    "Carpenter",
    "Cement Mason",
    "Chef",
    "Chemical Equipment Operator",
    "Child",
    "Credit Counselor",
    "Dining Room And Cafeteria Attendant",
    "Emergency Medical Technician",
    "Farming",
    "Firefighter",
    "First-line Supervisors Of Landscaping",
    "Fish And Game Warden",
    "Gaming Change Person",
    "Geological And Petroleum Technician",
    "Gynecologist",
    "Healthcare Support Occupation",
    "Historian ",
    "Host And Hostess ",
    "Hostess",
    "Interaction Designer ",
    "Janitor ",
    "Job Printer ",
    "Animal Control Worker",
    "Archivist",
    "Biophysicist",
    "Broadcast News Analyst",
    "Building And Grounds Cleaning And Maintenance Occupation",
    "Busines",
    "Chauffeur",
    "Clinical",
    "Commercial Pilot",
    "Counter And Rental Clerk",
    "Diesel Engine Specialist",
    "Economist",
    "Electrical Engineer",
    "Explosives Worker",
    "Financial Specialist",
    "Fire Inspector",
    "Fitter",
    "Food Preparation And Serving Related Worker",
    "Gas Plant Operator",
    "Grader",
    "Housekeeper ",
    "Human Resource Director ",
    "Immigration Inspector Or Customs Inspector ",
    "Information And Record Clerk",
    "Instructional Coordinator",
    "Insurance Sales Agent ",
    "Irradiated-fuel Handler ",
    "Jailer",
    "Avionics Technicians ",
    "Biomedical Engineer",
    "Chief Executive",
    "Chiropractor",
    "Cleaning",
    "Coache",
    "Communications Teacher",
    "Computer Programmer",
    "Concierge",
    "Cutting And Slicing Machine Setter",
    "Dental Hygienist",
    "Drilling And Boring Machine Tool Setter",
    "Engine And Other Machine Assembler",
    "Executive Administrative Assistant",
    "Extruding And Drawing Machine Setter",
    "First-line Supervisors Of Fire Fighting And Prevention Worker",
    "Gaming Supervisor",
    "Hvac Mechanic ",
    "Health Educator",
    "Insurance Appraiser ",
    "Aircraft Cargo Handling Supervisor",
    "Area",
    "Biological Science Teacher",
    "Brickmason",
    "Chemical Technician",
    "Chemistry Teacher",
    "Computer-controlled Machine Tool Operator",
    "Construction And Extraction Occupation",
    "Correspondence Clerk",
    "Education Administrator",
    "Education Teacher",
    "Electric Motor",
    "Emergency Management Director",
    "Engineering Technician",
    "Executive Secretarie",
    "Health Information Technician",
    "Information Systems Manager ",
    "Instructional Coordinator ",
    "Insulation Worker",
    "Insurance Investigator ",
    "Interpreter",
    "Judge",
    "Adjuster",
    "Adult Basic And Secondary Education And Literacy Teacher",
    "Agricultural And Food Science Technician",
    "Airfield Operations Specialist",
    "Ambulance Driver",
    "Animal Trainer",
    "Art Director",
    "Automotive Body And Related Repairer",
    "Baggage Porter",
    "Boiler Operator",
    "Cashier",
    "Chemical Plant And System Operator",
    "Clergy",
    "Computer Hardware Engineer",
    "Construction And Related Worker",
    "Counter Attendant",
    "Curator",
    "Customer Service Representative",
    "Dishwasher",
    "Entertainment Attendant",
    "Environmental Science Teacher",
    "Epidemiologist",
    "Farmer",
    "First-line Supervisors Of Food Preparation And Serving Worker",
    "First-line Supervisors Of Protective Service Worker",
    "Forest And Conservation Technician",
    "Gas Compressor And Gas Pumping Station Operator",
    "Heavy And Tractor-trailer Truck Driver",
    "Home Economics Teacher",
    "Horticultural Worker ",
    "Housekeeping Cleaner",
    "Hydrologist",
    "Janitorial Supervisor ",
    "Actuary",
    "Aerobics Instructor",
    "Accountant",
    "Animal Scientist",
    "Actor",
    "Advertising And Promotions Manager",
    "Archeologist",
    "Architect",
    "Athlete",
    "Audio And Video Equipment Technician",
    "Biological Technician",
    "Camera Operator",
    "Chemical Engineer",
    "Cleaners Of Vehicle",
    "Computer Occupation",
    "Crushing",
    "Drywall And Ceiling Tile Installers ",
    "Electrical And Electronics Drafter",
    "Electrical And Electronics Installer",
    "Electrician",
    "Electromechanical Equipment Assembler",
    "Extruding And Forming Machine Setter",
    "Fabricator",
    "Farm And Home Management Advisor",
    "Film And Video Editor",
    "Flight Attendant",
    "Forging Machine Setter",
    "Graphic Designer",
    "Health Diagnosing And Treating Practitioner",
    "Health And Safety Engineer",
    "Healthcare Practitioner",
    "Heat Treating Equipment Setter",
    "Hydrologist ",
    "Information Security Analyst",
    "Inspector",
    "Insulation Installer ",
    "Insurance Policy Processing Clerk ",
    "Agricultural Engineer",
    "Airline Pilot",
    "Appraiser",
    "Bartender",
    "Bridge And Lock Tender",
    "Building Cleaning Worker",
    "Camera And Photographic Equipment Repairer",
    "Cargo And Freight Agent",
    "Carpet Installer",
    "Commercial And Industrial Designer",
    "Communications Equipment Operator",
    "Community And Social Service Specialist",
    "Computer And Information Research Scientist",
    "Continuous Mining Machine Operator",
    "Correctional Treatment Specialist",
    "Counselor",
    "Dietetic Technician",
    "Earth Driller",
    "Electro-mechanical Technician",
    "Entertainer",
    "Equipment",
    "File Clerk",
    "First-line Supervisors Of Personal Service Worker",
    "Fitness Trainer",
    "Floor Sander",
    "Food Preparation Worker",
    "Forensic Science Technician",
    "Forester",
    "Funeral Service Manager",
    "Furniture Finisher",
    "Gaming Manager",
    "Health Specialties Teacher",
    "History Teacher",
    "Home Appliance Repairer",
    "Home Economics Teacher ",
    "Home Health Aide",
    "Industrial-organizational Psychologist ",
    "Insurance Underwriter ",
    "Amusement And Recreation Attendant",
    "Anthropologist",
    "Anthropology And Archeology Teacher",
    "Architectural And Engineering Manager",
    "Artist",
    "Audiologist",
    "Bu",
    "Cardiovascular Technologist",
    "Chemist",
    "Community And Social Service Occupation",
    "Computer Operator",
    "Computer Support Specialist",
    "Conservator",
    "Cooling And Freezing Equipment Operator",
    "Copy Marker",
    "Court Reporter",
    "Craft Artist",
    "Electrical And Electronic Equipment Assembler",
    "Electronic Home Entertainment Equipment Installer",
    "Excavating And Loading Machine And Dragline Operator",
    "Faller",
    "Fence Erector",
    "Financial Analyst",
    "Finisher",
    "Gaming Service Worker",
    "Gaming Surveillance Officer",
    "Geoscientist",
    "Hairdresser",
    "Head Cook",
    "Human Resources Assistant",
    "Industrial Engineer",
    "Industrial Production Manager ",
    "Insurance Claim",
    "Interviewer",
    "Assessors Of Real Estate",
    "Architecture And Engineering Occupation",
    "Assembler",
    "Atmospheric",
    "Automotive And Watercraft Service Attendant",
    "Bookkeeping",
    "Bartender Helper",
    "Brokerage Clerk",
    "Booth Cashier",
    "Butcher",
    "Cartographer",
    "Commercial Diver",
    "Control And Valve Installer",
    "Cutting",
    "Conveyor Operator",
    "Data Entry Keyer",
    "Credit Authorizer",
    "Economics Teacher",
    "Demonstrator",
    "Electrical And Electronics Repairer",
    "Dental Laboratory Technician",
    "Eligibility Interviewer",
    "Dredge Operator",
    "Embalmer",
    "Engineering Teacher",
    "English Language And Literature Teacher",
    "Fabric And Apparel Patternmaker",
    "First-line Supervisors Of Correctional Officer",
    "Farmworker",
    "Fashion Designer",
    "First-line Supervisors Of Mechanic",
    "First-line Supervisors Of Non-retail Sales Worker",
    "Financial Manager",
    "First-line Supervisors Of Retail Sales Worker",
    "First-line Supervisors Of Production And Operating Worker",
    "Food Preparation And Serving Related Occupation",
    "Floor Layer",
    "Grinding And Polishing Worker",
    "Food And Tobacco Roasting",
    "Foreign Language And Literature Teacher",
    "Health Technologist",
    "Forest And Conservation Worker",
    "Historian",
    "Home ",
    "Forestry And Conservation Science Teacher",
    "Fundraising Manager",
    "Home Appliance Installer ",
    "House Cleaner ",
    "General And Operations Manager",
    "Grinding",
    "Housekeeping Supervisor ",
    "Highway Maintenance Worker",
    "Hunter",
    "Human Resources Manager",
    "Industrial Engineering Technician",
    "Hunter And Trapper ",
    "Industrial Safety Engineer ",
    "Industrial Production Manager",
    "Janitor",
    "Instrument Sales Representative ",
    "Anesthesiologist",
    "Atmospheric And Space Scientist",
    "Baker",
    "Broadcast Technician",
    "Business Managers Of Artist",
    "Caster",
    "Childcare Worker",
    "Computer Systems Analyst",
    "Construction And Building Inspector",
    "Courier",
    "Court",
    "Elementary School Teacher",
    "Family And General Practitioner",
    "First-line Supervisors Of Helper",
    "Funeral Attendant",
    "Gaming Investigator",
    "Hr Specialist ",
    "Home Entertainment Equipment Installer ",
    "Hotel Desk Clerk ",
    "Industrial Engineer ",
    "Industrial Engineering Technician ",
    "Industrial-organizational Psychologist",
    "Inspector ",
    "Internist ",
    "Auditor",
    "Biochemist",
    "Biological Scientist",
    "Buyer",
    "Choreographer",
    "Compensation",
    "Computer",
    "Computer Numerically Controlled Machine Tool Programmer",
    "Computer And Information Systems Manager",
    "Credit Analyst",
    "Crossing Guard",
    "Dancer",
    "Drafter",
    "Educational",
    "Electronic Equipment Installer",
    "Environmental Engineering Technician",
    "Environmental Science And Protection Technician",
    "Fabric Mender",
    "Farm Equipment Mechanic",
    "First-line Supervisors Of Housekeeping And Janitorial Worker",
    "Food Scientist",
    "Food Server",
    "Gaming Dealer",
    "Geographer",
    "Human Resources Manager ",
    "Industrial Truck And Tractor Operator",
    "Agent",
    "Animator",
    "Arbitrator",
    "Athletic Trainer",
    "Authors ",
    "Bicycle Repairer",
    "Billing And Posting Clerk",
    "Bus Driver",
    "Business Teacher",
    "Changer",
    "Civil Engineering Technician",
    "Cleaner",
    "Coating",
    "Computer Science Teacher",
    "Criminal Justice And Law Enforcement Teacher",
    "Cutter",
    "Dentist",
    "Desktop Publisher",
    "Director",
    "Dispatcher",
    "Driver/sales Worker",
    "Education",
    "Elevator Installer",
    "Financial Operations Occupation",
    "Home Health Aide ",
    "Host",
    "Human Resource Manager ",
    "Industrial Equipment Maintenance ",
    "Infantry ",
    "Instructor",
    "Insurance Sales Agent",
    "Interior Designer",
    "Internist",
    "Jewelry Model Or Mold Makers ",
    "Library Science Teacher ",
    "Landscaper ",
    "Landscaping ",
    "Locomotive Firer",
    "Judge ",
    "Locksmith ",
    "Locomotive Engineer ",
    "Lodging Manager",
    "Mail Machine Operator ",
    "Marketing Manager",
    "Meat Packer ",
    "Medical Assistant",
    "Medical Records Technician ",
    "Medical And Health Services Manager",
    "Middle School Teacher ",
    "Mine Cutting And Channeling Machine Operator",
    "Mixing And Blending Machine Operator ",
    "Multimedia Artist",
    "Museum Technician",
    "Musician ",
    "Nursing Aide",
    "Obstetrician ",
    "Oil And Gas Operator ",
    "Parking Enforcement Worker ",
    "Pesticide Sprayer ",
    "Pharmacy Aide ",
    "Physical Therapist ",
    "Physician Assistant",
    "Physician Assistant ",
    "Political Science Teacher",
    "Political Science Teacher ",
    "Postal Clerk ",
    "Postal Service Mail Sorter",
    "License Clerk ",
    "Loading Machine Operator",
    "Machinist",
    "Makeup Artist",
    "Management Analyst ",
    "Manufactured Building And Mobile Home Installer",
    "Mathematical Science Occupation",
    "Meat Cutter",
    "Meat Packer",
    "Medical Secretary",
    "Metal Pourer And Caster ",
    "Metal Worker",
    "Mine Cutting Machine Operator ",
    "Mold Maker ",
    "Movie Director Or Theatre Director ",
    "Network Systems Analyst ",
    "Nonfarm Animal Caretaker ",
    "Numerical Control Machine Tool Operator ",
    "Occupational Therapist",
    "Office Clerk",
    "Optician",
    "Outdoor Power Equipment And Other Small Engine Mechanic",
    "Paper Goods Machine Operator ",
    "Paving",
    "Paving Equipment Operator ",
    "Personal Care Aide",
    "Personnel Recruiter ",
    "Pesticide Handler",
    "Petroleum Pump System Operator ",
    "Pharmacist ",
    "Physician ",
    "Pipelaying Fitter ",
    "Platemaker ",
    "Poet Or Lyricist ",
    "Postal Service Mail Carrier ",
    "Power Plant Operator",
    "Precision Devices Inspector ",
    "Layout Worker",
    "Legal Secretary",
    "Legal Secretary ",
    "Logging Equipment Operator ",
    "Management Occupation",
    "Manicurist",
    "Marine Oiler ",
    "Mathematical Science Teacher ",
    "Mechanical Engineering Technician ",
    "Medical Appliance Technician ",
    "Medical And Clinical Laboratory Technologist",
    "Metal Fabricator ",
    "Mining Engineer Or Geological Engineer ",
    "Mixing And Blending Machine Setter",
    "Motorboat Mechanic ",
    "Municipal Court Clerk ",
    "Municipal Fire Fighter ",
    "Musician",
    "Natural Sciences Manager",
    "Nuclear Engineer",
    "Nuclear Technician ",
    "Nutritionist",
    "Occupational Health And Safety Specialist",
    "Order Filler Or Stock Clerk ",
    "Orthotist",
    "Pediatricians ",
    "Pest Control Worker ",
    "Pharmaceutical Sales Representative ",
    "Pipefitter ",
    "Plumber ",
    "Logistician ",
    "Marcom Director ",
    "Manager",
    "Manufacturing Sales Representative ",
    "Material Moving Worker ",
    "Materials Scientist",
    "Mathematician ",
    "Mechanical Drafter ",
    "Media And Communication Equipment Worker",
    "Messenger",
    "Metal-refining Furnace Operator ",
    "Model Maker",
    "Multi-media Artist ",
    "Musical Instrument Repairer",
    "Network Admin Or Computer Systems Administrator ",
    "Operations Research Analyst ",
    "Patrol Officer ",
    "Performer",
    "Personal Care And Service Occupation",
    "Petroleum Pump Operator ",
    "Plastic Molding Machine Operator ",
    "Plating Operator ",
    "Podiatrist ",
    "Pourer",
    "Landscaping And Groundskeeping Worker",
    "Laboratory Animal Caretaker",
    "Law Clerk ",
    "Lay-out Worker ",
    "Library Worker ",
    "Life Scientists ",
    "Lifeguard ",
    "Machine Feeder ",
    "Manager Of Food Preparation ",
    "Material Moving Worker",
    "Mental Health Counselor",
    "Merchandise Displayer",
    "Meter Mechanic ",
    "Mining And Geological Engineer",
    "Motorcycle Mechanic ",
    "Movers ",
    "Music Arranger And Orchestrator ",
    "Occupational Health And Safety Technician",
    "Occupational Therapy Aide",
    "Office Machine Operator ",
    "Pr Manager ",
    "Packager",
    "Painting Machine Operator ",
    "Parts Salesperson ",
    "Pediatrician",
    "Pedicurist",
    "Personal Trainer ",
    "Pharmacist",
    "Photographer",
    "Physicist ",
    "Postal Service Clerk ",
    "Law Enforcement Teacher ",
    "Lawyer ",
    "Locomotive Engineer",
    "Marcom Manager ",
    "Mail Clerk ",
    "Management Analyst",
    "Manufactured Building Installer ",
    "Marine Cargo Inspector ",
    "Marriage And Family Therapist",
    "Mathematician",
    "Media And Communication Worker",
    "Medical Sales Representative ",
    "Motor Vehicle Inspector ",
    "Music Composer ",
    "New Accounts Clerk",
    "Night Shift ",
    "Occupational Therapist Aide ",
    "Operating Engineer ",
    "Ophthalmic Laboratory Technician",
    "Opticians ",
    "Orthodontist",
    "Packer And Packager ",
    "Photographic Developer ",
    "Photographic Process Worker ",
    "Pile-driver Operator",
    "Plasterer Or Stucco Mason ",
    "Kindergarten Teacher ",
    "Lawn Service Manager ",
    "Laundry Or Dry-cleaning Worker ",
    "Law Teacher",
    "Legislator",
    "Library Technician",
    "Logisticians ",
    "Maid ",
    "Mail Superintendent",
    "Maintenance Worker ",
    "Manager Tactical Operations ",
    "Manager Of Weapons Specialists ",
    "Marine Architect ",
    "Market Research Analyst",
    "Marking Machine Operator ",
    "Massage Therapist",
    "Medical Equipment Preparer",
    "Medical Scientists ",
    "Mental Health Counselor ",
    "Motor Vehicle Operator",
    "Motor Vehicle Operator ",
    "Municipal Fire Fighting Supervisor ",
    "Network And Computer Systems Administrator",
    "Nursing Instructor",
    "Nursing Instructor ",
    "Occupational Therapist ",
    "Office And Administrative Support Worker",
    "Personal Care Worker ",
    "Petroleum Technician ",
    "Plate Finisher ",
    "Plating And Coating Machine Setter",
    "Plumber",
    "Portable Power Tool Repairer ",
    "Potter ",
    "Precious Stone Worker ",
    "Licensed Practical And Licensed Vocational Nurse",
    "Loan Counselor ",
    "Machinery Maintenance ",
    "Maid",
    "Manicurists ",
    "Materials Engineer ",
    "Mathematical Scientist ",
    "Mechanical Drafter",
    "Medical Scientist",
    "Medical Transcriptionist",
    "Medical Transcriptionist ",
    "Middle School Teacher",
    "Molding Machine Operator ",
    "Motion Picture Projectionist ",
    "Motorboat Mechanic",
    "Music Director ",
    "Night Security Guard ",
    "Nuclear Power Reactor Operator",
    "Numerical Tool Programmer Or Process Control Programmer ",
    "Order Clerk ",
    "Packer",
    "Painting",
    "Photographer ",
    "Photographic Restorer ",
    "Physical Therapist Aide",
    "Physical Therapist Aide ",
    "Physical Therapist Assistant",
    "Police And Sheriff's Patrol Officer",
    "Precious Stone And Metal Worker",
    "Lathe Operator ",
    "Landscape Architect ",
    "Keyboard Instrument Repairer And Tuner ",
    "Law Teacher ",
    "Life Science Technician ",
    "Loan Interviewer ",
    "Loan Officer ",
    "Locomotive Firer ",
    "Maintenance Worker",
    "Materials Scientist ",
    "Mechanical Engineer ",
    "Mechanical Inspector ",
    "Military Officer ",
    "Milling Machine Operator ",
    "Molder",
    "Nuclear Monitoring Technician ",
    "Nursery Worker ",
    "Office Machine Operator",
    "Office Machine And Cash Register Servicer ",
    "Offset Lithographic Press Operator ",
    "Packaging Machine Operator ",
    "Payroll Clerk ",
    "Personal Financial Advisor",
    "Photographic Process Worker",
    "Photographic Reproduction Technician ",
    "Physical Scientist",
    "Physicist",
    "Physics Teacher",
    "Physics Teacher ",
    "Police And Sheriffs Patrol Officer ",
    "Postal Service Mail Sorter ",
    "Legal Assistant",
    "Legal Support Worker",
    "Log Grader And Scaler ",
    "Logging Equipment Operator",
    "Maintenance Equipment Operator ",
    "Marketing Manager ",
    "Marriage And Family Therapist ",
    "Medical Appliance Technician",
    "Mine Shuttle Car Operator",
    "Museum Conservator ",
    "Musician Or Singer ",
    "Natural Sciences Manager ",
    "New Accounts Clerk ",
    "Nuclear Engineer ",
    "Office And Administrative Support Worker ",
    "Oral Surgeon ",
    "Oral And Maxillofacial Surgeon",
    "Order Filler ",
    "Outdoor Power Equipment Mechanic ",
    "Parking Enforcement Worker",
    "Personal Service Worker ",
    "Pharmacy Technician",
    "Pharmacy Technician ",
    "Photoengraving Machine Operator ",
    "Pipe Fitter ",
    "Pipelayer ",
    "Police Detective ",
    "Postal Service Mail Carrier",
    "Postmasters ",
    "Precision Aircraft Systems Assemblers ",
    "Lathe And Turning Machine Tool Setter",
    "Kindergarten Teacher",
    "Laborer",
    "Landscape Artist ",
    "Laundry And Dry-cleaning Worker",
    "Lawyer",
    "Library Technician ",
    "Mail Clerk",
    "Mapping Technician ",
    "Market Research Analyst ",
    "Materials Engineer",
    "Mechanical Engineer",
    "Mechanical Engineering Technician",
    "Media And Communication Worker ",
    "Medical Laboratory Technologist ",
    "Motion Picture Projectionist",
    "Music Director",
    "Naval Architects ",
    "Nuclear Medicine Technologist",
    "Nursing Aide ",
    "Ophthalmic Laboratory Technician ",
    "Orthotist Or Prosthetist ",
    "Paperhanger",
    "Pastry Chef ",
    "Personal Home Care Aide ",
    "Pharmacy Aide",
    "Physician",
    "Plant And System Operator ",
    "Legal Support Worker ",
    "Librarian",
    "Loading Machine Operator ",
    "Log Grader",
    "Mail Machine Operator",
    "Manager ",
    "Marine Engineer",
    "Mathematical Science Teacher",
    "Mechanical Equipment Sales Representative ",
    "Metal Molding Operator ",
    "Millwright",
    "Millwright ",
    "Molder ",
    "Molding And Casting Worker ",
    "Nuclear Power Reactor Operator ",
    "Optometrist ",
    "Organizational Development Manager ",
    "Painter And Illustrator ",
    "Paralegal",
    "Park Naturalist ",
    "Parts Salesperson",
    "Pest Control Worker",
    "Pewter Caster ",
    "Pile-driver Operator ",
    "Plant And System Operator",
    "Policy Processing Clerk",
    "Postsecondary Education Administrators ",
    "Legal Occupation",
    "Letterpress Setters Operator ",
    "Librarian ",
    "Library Assistant",
    "Licensed Practical Nurse ",
    "Loan Officer",
    "Locksmith",
    "Logging Worker",
    "Logging Worker ",
    "Machine Feeder",
    "Machine Operator ",
    "Maintenance Supervisor ",
    "Marine Engineer ",
    "Marketing Specialist",
    "Mathematical Technician",
    "Mechanic",
    "Meter Reader",
    "Mining Machine Operator",
    "Motorboat Operator ",
    "Multiple Machine Tool Setter ",
    "Municipal Clerk ",
    "Naval Architect",
    "Occupational Health Safety Technician ",
    "Occupational Therapist Assistant ",
    "Occupational Therapy Assistant",
    "Oil Service Unit Operator ",
    "Operations Research Analyst",
    "Orthodontist ",
    "Pantograph Engraver ",
    "Paralegal ",
    "Parking Lot Attendant",
    "Petroleum Pump System Operator",
    "Physical Scientist ",
    "Plastic Worker",
    "Podiatrist",
    "Postsecondary Teacher",
    "Landscape Architect",
    "Judicial Law Clerk",
    "Legislator ",
    "Licensing Examiner And Inspector ",
    "Life Scientist",
    "Loan Interviewer",
    "Locker Room Attendant ",
    "Logging Supervisor ",
    "Maintenance And Repair Worker",
    "Marking Clerk ",
    "Massage Therapist ",
    "Materials Inspector ",
    "Mathematical Technician ",
    "Mechanical Door Repairer",
    "Medical Equipment Repairer",
    "Medical Secretary ",
    "Microbiologist",
    "Microbiologist ",
    "Multiple Machine Tool Setter",
    "Musical Instrument Tuner ",
    "Nonfarm Animal Caretaker",
    "Nuclear Technician",
    "Nursery Manager ",
    "Nutritionist ",
    "Optical Instrument Assembler ",
    "Optometrist",
    "Packaging And Filling Machine Operator",
    "Paperhanger ",
    "Paste-up Worker ",
    "Patternmaker",
    "Physical Therapist",
    "Pipelayer",
    "Plating Operator Or Coating Machine Operator ",
    "Postmaster",
    "Power Distributor",
    "Power Plant Operator ",
    "Library Assistant ",
    "Library Science Teacher",
    "Light Truck Or Delivery Services Driver",
    "Machinist ",
    "Marketing Vp ",
    "Material Movers ",
    "Medical Equipment Preparer ",
    "Metal-refining Furnace Operator",
    "Mining Machine Operator ",
    "Mobile Heavy Equipment Mechanic",
    "Nuclear Equipment Operation Technician ",
    "Nuclear Medicine Technologist ",
    "Obstetrician",
    "Occupational Health Safety Specialist ",
    "Order Filler",
    "Parking Lot Attendant ",
    "Payroll And Timekeeping Clerk",
    "Personal Care And Service Worker",
    "Personal Financial Advisor ",
    "Petroleum Engineer",
    "Petroleum Engineer ",
    "Philosophy And Religion Teacher",
    "Photoengraver ",
    "Photographic Processing Machine Operator ",
    "Plant Scientist ",
    "Plating Machine Operator ",
    "Police Identification Or Records Officer ",
    "Postal Service Clerk",
    "Postsecondary Teacher ",
    "Power Generating Plant Operator ",
    "Lifeguard",
    "Lodging Manager ",
    "Logging Tractor Operator ",
    "Machine Tool Operator ",
    "Maintenance And Repair Worker ",
    "Makeup Artists ",
    "Manager Of Air Crew ",
    "Marine Oiler",
    "Medical Assistant ",
    "Medical Technician ",
    "Medical And Clinical Laboratory Technician",
    "Mental Health And Substance Abuse Social Worker",
    "Merchandise Displayer Or Window Trimmer ",
    "Metal Worker ",
    "Milling And Planing Machine Setter",
    "Model Maker ",
    "Motorboat Operator",
    "Motorcycle Mechanic",
    "Office Clerk ",
    "Online Marketing Analyst ",
    "Operating Engineer",
    "Order Clerk",
    "Other Construction Equipment Operator",
    "Painter",
    "Paper Goods Machine Setter",
    "Paramedic",
    "Percussion Instrument Repairer ",
    "Philosophy And Religion Teacher ",
    "Photogrammetrist",
    "Physical Therapist Assistant ",
    "Plasterer",
    "Plumber Or Pipefitter Or Steamfitter ",
    "Political Scientist",
    "Political Scientist ",
    "Poultry Cutter ",
    "Power Distributors Or Dispatcher ",
    "Precision Dyer ",
    "Prepress Technician",
    "Pressure Vessel Inspector ",
    "Pressing Machine Operator ",
    "Precision Printing Worker ",
    "Prevention Specialist",
    "Precision Pattern And Die Caster ",
    "Printing Press Machine Operator ",
    "Preschool Teacher ",
    "Private Detective And Investigator ",
    "Production Planner ",
    "Production Planning ",
    "Project Manager ",
    "Psychiatric Aide ",
    "Pump Operators ",
    "Radar Technician ",
    "Radio Operator",
    "Railroad Inspector ",
    "Record Clerk ",
    "Recreation And Fitness Studies Teacher",
    "Related Worker",
    "Rental Clerk ",
    "Reporters Or Correspondent ",
    "Runner",
    "Scaler",
    "Sewer",
    "Shampooer",
    "Sheet Metal Worker",
    "Sheet Metal Worker ",
    "Shoe And Leather Worker",
    "Social Media Marketing Manager ",
    "Social Work Teacher",
    "Soil Scientist Or Plant Scientist ",
    "Sports Book Writer ",
    "Steel Worker ",
    "Stucco Mason",
    "Supervisor Correctional Officer ",
    "Survey Researcher",
    "Surveyor ",
    "Tailor",
    "Valve Repairer Or Regulator Repairer ",
    "Vocational Education Teacher ",
    "Welding",
    "Woodworker",
    "Print Binding And Finishing Worker",
    "Producer",
    "Property",
    "Psychiatrist",
    "Psychiatrist ",
    "Rn ",
    "Rail Transportation Worker ",
    "Recordkeeping Clerk ",
    "Refractory Materials Repairer",
    "Refuse And Recyclable Material Collector",
    "Registered Nurse ",
    "Religious Worker ",
    "Respiratory Therapy Technician ",
    "Retail Salesperson",
    "Sailor",
    "Security Systems Installer Or Fire Alarm Systems Installer ",
    "Signal And Track Switch Repairer",
    "Sociology Teacher ",
    "Solderer ",
    "Sorter",
    "Statistician ",
    "Stripper ",
    "Technical Writer ",
    "Traffic Technician",
    "Transportation Inspector ",
    "Transportation Security Screener",
    "Upholsterer ",
    "Waitress ",
    "Watch Repairer",
    "Welder ",
    "Product Promoter ",
    "Purchasing Manager",
    "Railroad Switch Operator ",
    "Repairer",
    "Reservation Agent Or Transportation Ticket Agent ",
    "Retail Salesperson ",
    "Rock Splitter ",
    "Sales Engineer ",
    "Sawing Machine Operator ",
    "Semiconductor Processor ",
    "Service Unit Operator",
    "Ship Engineer ",
    "Special Force ",
    "Stationary Engineer",
    "Substance Abuse And Behavioral Disorder Counselor",
    "Surveying Technician ",
    "Sys Admin ",
    "Taxi Driver",
    "Taxi Drivers And Chauffeur ",
    "Telemarketer ",
    "Textile Knitting And Weaving Machine Setter",
    "Transit And Railroad Police",
    "Transportation Attendant",
    "Transportation Worker",
    "Travel Agent ",
    "Veterinarian",
    "Water And Wastewater Treatment Plant And System Operator",
    "Web Developer ",
    "Welder",
    "Woodworking Machine Setter",
    "Procurement Clerk",
    "Prosthodontist",
    "Public Relation",
    "Railroad Conductor",
    "School Bus Driver ",
    "Social And Human Service Assistant ",
    "Soil Conservationist ",
    "Sound Engineering Technician ",
    "Staff Psychologist ",
    "Statistical Assistant",
    "Stock Clerk",
    "Streetcar Operator ",
    "Supervisor Fire Fighting Worker ",
    "Survey Researcher ",
    "Technical Specialist ",
    "Tender",
    "Textile Bleaching And Dyeing Machine Operator",
    "Tool And Die Maker ",
    "Transportation Equipment Painters ",
    "Vice President Of Marketing ",
    "Waiter ",
    "Weapons Specialists ",
    "Wellhead Pumper",
    "Prepress Technician ",
    "Press Machine Setter, Operator ",
    "Presser",
    "Private Detective",
    "Product Safety Engineer ",
    "Proofreaders And Copy Marker ",
    "Pruner",
    "Psychologist ",
    "Punching Machine Setters ",
    "Radiation Therapist ",
    "Radiologic Technologist",
    "Railroad Brake",
    "Recyclable Material Collector ",
    "Residential Advisor ",
    "Rigger",
    "Rough Carpenter ",
    "Sales Manager",
    "Sculptor ",
    "Secondary School Teacher",
    "Ship Engineer",
    "Short Order Cook ",
    "Shuttle Car Operator ",
    "Slaughterer",
    "Tsa ",
    "Technician",
    "Telemarketer",
    "Tire Builder",
    "Title Searcher ",
    "Tool Sharpener ",
    "Trainer ",
    "Transportation Equipment Maintenance ",
    "Trapper",
    "Underground Mining ",
    "Utility Meter Reader ",
    "Veterinary Technician ",
    "Welfare Eligibility Clerk ",
    "Writer",
    "Probation Officers And Correctional Treatment Specialist ",
    "Product Management Leader ",
    "Professor ",
    "Prosthodontist ",
    "Public Transportation Inspector ",
    "Radiologic Technologist ",
    "Real Estate Sales Agent",
    "Receptionist",
    "Recreational Therapist ",
    "Rigger ",
    "Sales And Related Workers ",
    "Secondary School Teacher ",
    "Semiconductor Processor",
    "Sketch Artist ",
    "Skincare Specialist",
    "Space Sciences Teacher ",
    "Stock Clerk ",
    "Storage Manager Or Distribution Manager ",
    "Surgical Technologist",
    "Surveying And Mapping Technician ",
    "Teacher",
    "Teller",
    "Terrazzo Workes And Finisher ",
    "Textile Dyeing Machine Operator ",
    "Textile Knitting Machine Operator ",
    "Tire Builder ",
    "Tool Set-up Operator ",
    "Training And Development Manager",
    "Transit Police Or Railroad Police ",
    "Travel Guide ",
    "Tree Trimmer",
    "Woodworking Machine Setter ",
    "Preschool Education Administrators ",
    "Production Inspector ",
    "Purchasing Agent",
    "Processing Machine Operator",
    "Real Estate Broker ",
    "Production",
    "Rehabilitation Counselor",
    "Production Control Manager ",
    "Rolling Machine Setter ",
    "Production Helper ",
    "Roof Bolter",
    "Production Worker ",
    "Segmental Paver ",
    "Public Health Social Worker ",
    "Self-enrichment Education Teacher ",
    "Public Relations Specialist",
    "Public Relations Specialist ",
    "Set And Exhibit Designer",
    "Receptionist And Information Clerk ",
    "Sewing Machine Operator ",
    "Recreational Therapist",
    "Sheriff ",
    "Related Fishing Worker",
    "Ship Mates ",
    "Reservation And Transportation Ticket Agent",
    "Ship Pilot ",
    "Sewing Machine Operator",
    "Slot Key Person ",
    "Soil Scientist ",
    "Slot Supervisor",
    "Special Education Teacher",
    "Social Sciences Teacher ",
    "Statement Clerk ",
    "Social Scientists ",
    "Statistical Assistant ",
    "Social And Human Service Assistant",
    "Supervisor Of Police ",
    "Soldering Machine Setter ",
    "Surveying And Mapping Technician",
    "Sound Engineering Technician",
    "System Administrator ",
    "Stone Cutter ",
    "Tax Examiner ",
    "Structural Iron And Steel Worker ",
    "Technical Director ",
    "Teacher Assistant ",
    "Therapist ",
    "Timing Device Assembler",
    "Ticket Agent ",
    "Tractor-trailer Truck Driver ",
    "Tour Guide",
    "Traffic Technician ",
    "Transportation Worker ",
    "Training And Development Specialist",
    "Travel Clerk ",
    "Typesetter ",
    "Truck Mechanic",
    "University ",
    "User Experience Researcher ",
    "Umpire",
    "Usher ",
    "Veterinary Assistant",
    "Veterinary Technologist",
    "Vocational Education Teacher",
    "Waiter",
    "Waste Treatment Plant Operator ",
    "Well And Core Drill Operator ",
    "Precision Instrument And Equipment Repairer",
    "Printing Press Operator",
    "Production Worker",
    "Psychologist",
    "Psychology Teacher",
    "Radio Operator ",
    "Real Estate Sales Agent ",
    "Refinery Operator ",
    "Reinforcing Iron And Rebar Worker",
    "Respiratory Therapist",
    "Sawing Machine Tool Setter ",
    "Separating Machine Operators ",
    "Ship Carpenter And Joiner ",
    "Shoe And Leather Repairer ",
    "Signal Repairer Or Track Switch Repairer ",
    "Social Science Research Assistant ",
    "Spraying Machine Operator ",
    "Structural Metal Fabricator",
    "Structural Metal Fabricator ",
    "Technologist",
    "Textile Cutting Machine Setter",
    "Timing Device Assemblers ",
    "Trimmer",
    "Umpire And Referee ",
    "Washing Equipment Operator ",
    "Welder And Cutter ",
    "Wind Instrument Repairer ",
    "Private Household Cook ",
    "Procurement Clerk ",
    "Prosthetist",
    "Psychiatric Aide",
    "Psychology Teacher ",
    "Purchasing Manager ",
    "Radiologic Technologist And Technician ",
    "Rail Car Repairer",
    "Rail-track Laying And Maintenance Equipment Operator",
    "Real Estate Association Manager ",
    "Rehabilitation Counselor ",
    "Rotary Drill Operator ",
    "Sawing Machine Setter",
    "Scout",
    "Septic Tank Servicer",
    "Set Designer ",
    "Shear Machine Set-up Operator ",
    "State ",
    "Stevedore ",
    "Subway And Streetcar Operator",
    "Surgeon",
    "Tax Preparer ",
    "Textile Cutting Machine Operator ",
    "Textile Machine Operator ",
    "Tire Changer ",
    "Transportation Manager ",
    "Typesetting Machine Operator ",
    "Vending Machine Servicer ",
    "Visual Designer ",
    "Welding Machine Setter ",
    "Zoologist",
    "Precision Etcher And Engraver ",
    "Producers And Director ",
    "Professional Photographer ",
    "Printing Machine Operator ",
    "Product Promoter",
    "Product Specialist ",
    "Production Laborer ",
    "Production Manager ",
    "Protective Service Occupation",
    "Protective Service Worker",
    "Public Address System And Other Announcer",
    "Recreation And Fitness Studies Teacher ",
    "Religious Worker",
    "Rock Splitter",
    "Roofer",
    "Roustabouts ",
    "Security Guard",
    "Shipping",
    "Preschool Teacher",
    "Shoe Machine Operators ",
    "Private Sector Executive ",
    "Silversmith ",
    "Producer ",
    "Singer",
    "Production Occupation",
    "Social Scientist",
    "Radio And Television Announcer ",
    "Rail Yard Engineer",
    "Social Work Teacher ",
    "Sociologist",
    "Rail Yard Engineer ",
    "Sociologist ",
    "Range Manager ",
    "Specialist",
    "Refrigeration Mechanic ",
    "Roof Bolters Mining ",
    "Statistician",
    "Substation Maintenance ",
    "Roofer ",
    "Surveyor",
    "Sailor ",
    "Taper",
    "Sales Manager ",
    "Technical Occupation",
    "Scientific Photographer ",
    "Tire Repairer",
    "Secretary ",
    "Truck Driver ",
    "User Experience Manager ",
    "Singer ",
    "Waitress",
    "Speech-language Pathologist",
    "Window Trimmer",
    "Stationary Engineer ",
    "Stonemason",
    "Yardmaster",
    "Stringed Instrument Repairer And Tuner ",
    "Supervisor Of Customer Service ",
    "Surgical Technologist ",
    "Talent Director ",
    "Tank Car ",
    "Tax Preparer",
    "Terrazzo Worker",
    "Therapist",
    "Tool Grinder",
    "Typist",
    "Usher",
    "Veterinarian ",
    "Warehouse ",
    "Wellhead Pumper ",
    "Wholesale Buyer ",
    "Woodworker ",
    "Woodworking Machine Operator ",
    "Probation Officer",
    "Psychiatric Technician ",
    "Railroad Yard Worker ",
    "Real Estate Appraiser ",
    "Reporter",
    "Respiratory Therapy Technician",
    "Retail Sales Person ",
    "Rolling Machine Setter",
    "Sales Engineer",
    "Sales Representative ",
    "Scanner Operator ",
    "School Social Worker ",
    "Security Guard ",
    "Sewer Pipe Cleaner",
    "Shampooer ",
    "Social Service Specialists ",
    "Spotters ",
    "Stock Broker ",
    "Tailor ",
    "Tank Car",
    "Team Assembler",
    "Technical Program Manager ",
    "Telecommunications Line Installer",
    "Telephone Station Installer And Repairer ",
    "Title Examiner ",
    "Tool And Die Maker",
    "Transformer Repairer ",
    "Translator",
    "Travel Guide",
    "Urban Planner ",
    "Urban And Regional Planner",
    "Vice President Of Human Resources ",
    "Weigher",
    "Welder-fitter ",
    "Welding Machine Operator ",
    "Welding Machine Tender ",
    "Radio And Television Announcer",
    "Railroad Conductors ",
    "Real Estate Broker",
    "Recreational Vehicle Service Technician",
    "Residential Advisor",
    "Roustabout",
    "Safe Repairer",
    "Safety Engineer ",
    "Screen Printing Machine Operator ",
    "Segmental Paver",
    "Skin Care Specialist ",
    "Social Worker",
    "Sociology Teacher",
    "Software Developer",
    "Soil And Plant Scientist",
    "Stationary Engineer Or Boiler Operator ",
    "Substance Abuse Counselor ",
    "Substance Abuse Social Worker ",
    "Talent Acquisition Manager ",
    "Technical Worker",
    "Telephone Operator",
    "Tour Guide ",
    "Tractor Operator ",
    "Training Manager Or Development Manager ",
    "Transportation And Material-moving ",
    "Video Editor ",
    "Webmaster ",
    "Precision Lens Grinders And Polisher ",
    "Proofreader",
    "Psychiatric Technician",
    "Pump Operator",
    "Radiation Therapist",
    "Radio Mechanic ",
    "Rail Transportation Worker",
    "Recreation Worker",
    "Recruiter ",
    "Registered Nurse",
    "Restaurant Cook ",
    "Sales Representative",
    "Sawing Machine Setter ",
    "Secretary",
    "Securities Sales Agent ",
    "Security And Fire Alarm Systems Installer",
    "Self-enrichment Education Teacher",
    "Septic Tank Servicer ",
    "Set And Exhibit Designer ",
    "Shipping And Receiving Clerk ",
    "Social Science Research Assistant",
    "Social Sciences Teacher",
    "Social And Community Service Manager",
    "Special Forces Officer ",
    "Speech-language Pathologist ",
    "Sports Competitor",
    "Stone Sawyer ",
    "Stonemason ",
    "Telecommunications Equipment Installer",
    "Telecommunications Facility Examiner ",
    "Title Abstractor ",
    "Title Examiner",
    "Train Crew ",
    "Transportation Attendant ",
    "Travel Agent",
    "Tree Trimmer ",
    "Tuner",
    "Upholsterer",
    "Veterinary Assistant Or Laboratory Animal Caretaker ",
    "Wholesale And Retail Buyer",
    "Word Processor",
    "Writer Or Author ",
    "Precision Mold And Pattern Caster ",
    "Program Director ",
    "Public Relations Manager ",
    "Radiologic Technician ",
    "Recreation Worker ",
    "Respiratory Therapist ",
    "Rotary Drill Operator",
    "Sales Person ",
    "Service Station Attendant ",
    "Service Technician",
    "Ship Captain ",
    "Shoe Machine Operator",
    "Social Worker ",
    "Software Engineer ",
    "Special Education Teacher ",
    "Structural Iron And Steel Worker",
    "Switchboard Operator",
    "Taper ",
    "Tax Examiner",
    "Textile Worker ",
    "Tile Setter Or Marble Setter ",
    "Tile And Marble Setter",
    "Transportation Inspector",
    "Travel Clerk",
    "Word Processors And Typist ",
    'Computer Scientist',
    'IT Professional',
    'UX Designer & UI Developer',
    'SQL Developer',
    'Web Designer',
    'Web Developer',
    'Help Desk Worker/Desktop Support',
    'Software Engineer',
    'Data Entry',
    'DevOps Engineer',
    'Computer Programmer',
    'Network Administrator',
    'Information Security Analyst',
    'Artificial Intelligence Engineer',
    'Cloud Architect',
    'IT Manager',
    'Technical Specialist',
    'Application Developer',
    'Chief Technology Officer (CTO)',
    'Chief Information Officer (CIO)',
  ];